### PR TITLE
Fix gem name in gemspec to make it downloadable from Github

### PR DESCRIPTION
**Pull request by rhannequin**
By changing gem name from "bankin-api-ruby" to "bankin" we can download it from Github in Gemfile like this:

```rb
# Gemfile

gem 'bankin', github: 'quipuapp/bankin-api-ruby'
```

### CODE REVIEW

**Comment by uncoder** [comment]
Well, it's already can be downloaded from Github using the line in Gemfile like: 
```gem 'bankin-api-ruby', github: 'quipuapp/bankin-api-ruby'```
What's the point to change the name to *bankin*?

**Comment by rhannequin** [comment]
Hello,

Maybe I don't require it the right way, but none of these two examples work after downloading the `bankin-api-ruby` gem with Bundler:

```rb
# app.rb

require 'rubygems'
require 'bundler'
Bundler.require(:default)

puts Bankin.inspect
```

```rb
# app.rb

require 'bankin-api-ruby'

puts Bankin.inspect
```

But if I try this, it works:

```rb
# Gemfile

source "https://rubygems.org"
git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }
gem 'bankin', github: 'rhannequin/bankin-api-ruby', branch: 'fix-gem-name'


# app.rb

require 'rubygems'
require 'bundler'
Bundler.require(:default)

puts Bankin.inspect
```

**Comment by uncoder** [comment]
Hi,
_bankin-api-ruby_ is just a gem name. The class is **Bankin**, so you have to require _bankin_.

Try this:
```
# Gemfile

source 'https://rubygems.org'
gem 'bankin-api-ruby', github: 'quipuapp/bankin-api-ruby'


# app.rb

require 'rubygems'
require 'bundler'
Bundler.require(:default)

require 'bankin'

puts Bankin.inspect
```

**Comment by uncoder** [comment]
btw there is missing documentation for the gem,
use this as a quick start:

```ruby
Bankin.configure do |config|
  config.client_id = 'your_client_id'
  config.client_secret = 'your_client_secret''
end

puts Bankin::Bank.list.load_all!
```

**Comment by rhannequin** [comment]
Hello,

I still think it is a good idea to name the gem `bankin`.
When launching the gem with `bundle console` we have this error:

```rb
# bundle console

Bankin.configure {}
# => NoMethodError: undefined method `configure' for Bankin:Module
```

With gem name `bankin` it works:

```rb
# bundle console

Bankin.configure {}
# => nil
```

**Pull request closed without merging**
